version: "3"
services:
  db:
    image: postgres:11.5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  app:
    build: .
    command: npm run dev
    ports:
      - 4040:4040
    environment:
      PORT: 4040
    volumes:
      - ./:/app
